### ISSUE TITLE
Ability to change the marker color

### ISSUE THREAD

**Issue by ShankarKakumani** [Yrll21/googlemaps_flutter_webservices#1]
- please add support to add the color to the marker as well.

**Comment by Yrll21** [comment]
Hi! Please note that this library is for Google Maps Webservices (e.g. [Places API Web Services](https://developers.google.com/maps/documentation/places/web-service)) and is not intended for front end implementation of Google Maps APIs. For Front end flutter implementation of Google Maps, please see this package: https://pub.dev/packages/google_maps_flutter

Thanks for raising this, but I will have to close this issue now.

**Comment by ShankarKakumani** [comment]
Sorry, my mistake, I wasn't very clear.
I want to change the colors for markers in the StaticMap
